# Fast lane File
default_platform(:android)

platform :android do
  desc "Distribute production build to Firebase"
  lane :release_to_firebase do
    sh "flutter clean"
    sh "flutter build apk --release --flavor production --target lib/main_production.dart --no-tree-shake-icons"

    # List of testers
    testers_list = [
      "m9stafa05@gmail.com",
    ]

    # Convert array to comma-separated string
    testers_string = testers_list.join(", ")

    firebase_app_distribution(
      app: "1:651360984245:android:9d4247976ffb420071b2fc",
      firebase_cli_token: ENV["FIREBASE_CLI_TOKEN"],
      android_artifact_type: "APK",
      android_artifact_path: "../build/app/outputs/flutter-apk/app-production-release.apk",
      testers: testers_string,
      release_notes: "DocDoc App version(0.0.1) Auth Testing",
    )
  end
end